### ISSUE TITLE
File provider is not implemented correctly

### ISSUE THREAD

**Issue by xelld** [annetutil/annet#181]
Hello.
An exception thrown when trying to use the file provider.
Version: annet 0.16.26

For example with the following config:
```yaml
# context.yml
<...>
storage:
  default:
    adapter: file
    params:
      path: ~/Work/personal/annet-config/inventory.yaml
<...>

# inventory.yaml 
devices:
  - fqdn: hostname.fqdn.tld
    vendor: cisco
    interfaces:
      - name: Gi1
        description: test
```
Trying to "gen":
```bash
$ annet gen hostname.fqdn.tld
Traceback (most recent call last):
  File "/home/xelld/.local/bin/annet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/xelld/.local/lib/python3.12/site-packages/annet/annlib/lib.py", line 340, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xelld/.local/lib/python3.12/site-packages/annet/annet.py", line 19, in main
    return parser.dispatch(pre_call=annet.init, add_help_command=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xelld/.local/lib/python3.12/site-packages/annet/argparse.py", line 362, in dispatch
    return ns.func(*values)
           ^^^^^^^^^^^^^^^^
  File "/home/xelld/.local/lib/python3.12/site-packages/annet/cli.py", line 186, in gen
    with get_loader(args, args) as loader:
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/xelld/.local/lib/python3.12/site-packages/annet/cli.py", line 73, in get_loader
    storages.append(exit_stack.enter_context(connector.storage()(storage_opts)))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xelld/.local/lib/python3.12/site-packages/annet/adapters/file/provider.py", line 158, in storage_factory
    return FS(opts)
           ^^^^^^^^
TypeError: Can't instantiate abstract class FS without an implementation for abstract methods 'resolve_all_fdnds', 'search_connections'
```

**Comment by gescheit** [comment]
Try now. Fixed in https://github.com/annetutil/annet/pull/180 https://github.com/annetutil/annet/pull/183

**Comment by xelld** [comment]
It works now, thanks!
