### ISSUE TITLE
Annet diff - NotImplementedError()

### ISSUE THREAD

**Issue by lst123** [annetutil/annet#69]
Hello!

**Annet diff** raises NotImplementedError():
```
~/annet> annet diff testbox
Traceback (most recent call last):
  File "/Users/lst/Documents/py_prj/.venv/bin/annet", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/annlib/lib.py", line 340, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/annet.py", line 19, in main
    return parser.dispatch(pre_call=annet.init, add_help_command=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/argparse.py", line 360, in dispatch
    return ns.func(*values)
           ^^^^^^^^^^^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/cli.py", line 119, in diff
    gen_sort_diff(api.diff(args, loader, device_ids, filterer), args),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/api/__init__.py", line 335, in diff
    for res in ann_gen.old_new(
               ^^^^^^^^^^^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/gen.py", line 400, in old_new
    running, failed_running = _old_resolve_running(config, devices)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/tracing.py", line 139, in wrapper
    return cache(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/gen.py", line 812, in _old_resolve_running
    running, failed_running = fetcher.fetch(devices)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lst/Documents/py_prj/.venv/lib/python3.12/site-packages/annet/deploy.py", line 80, in fetch
    raise NotImplementedError()
NotImplementedError
```

**Comment by drtyrsa** [comment]
@lst123 Is it still relevant? If it is, can you please give some details about your setup: what is in your `context.yml`, what device are trying to connect to?
